version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fy-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - fy-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: fy-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - fy-network
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    container_name: fy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fy_database
      POSTGRES_USER: fy_user
      POSTGRES_PASSWORD: fy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fy-network

networks:
  fy-network:
    driver: bridge

volumes:
  postgres_data:
